<?php

use App\Product;
use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Product::create([
            'name' => 'MacBook Pro',
            'slug' => 'macbook-pro',
            'details' => '15 inch, 1TB HDD, 32GB RAM',
            'price' => 2499.99,
            'shipping_cost' => 29.99,
            'description' => 'MackBook Pro',
            'category_id' => 1,
            'brand_id' => 1,
            'image_path' => 'macbook-pro.png'
        ]);

        Product::create([
            'name' => 'Dell Vostro 3557',
            'slug' => 'vostro-3557',
            'details' => '15 inch, 1TB HDD, 8GB RAM',
            'price' => 1499.99,
            'shipping_cost' => 19.99,
            'description' => 'Dell Vostro 3557',
            'category_id' => 1,
            'brand_id' => 2,
            'image_path' => 'dell-v3557.png'
        ]);

        Product::create([
            'name' => 'iPhone 11 Pro',
            'slug' => 'iphone-11-pro',
            'details' => '6.1 inch, 64GB 4GB RAM',
            'price' => 649.99,
            'shipping_cost' => 14.99,
            'description' => 'iPhone 11 Pro',
            'category_id' => 2,
            'brand_id' => 1,
            'image_path' => 'iphone-11-pro.png'
        ]);

        Product::create([
            'name' => 'Remax 610D Headset',
            'slug' => 'remax-610d',
            'details' => '6.1 inch, 64GB 4GB RAM',
            'price' => 8.99,
            'shipping_cost' => 1.89,
            'description' => 'Remax 610D Headset',
            'category_id' => 3,
            'brand_id' => 3,
            'image_path' => 'remax-610d.jpg'
        ]);

        Product::create([
            'name' => 'Samsung LED TV',
            'slug' => 'samsung-led-24',
            'details' => '24 inch, LED Display, Resolution 1366 x 768',
            'price' => 41.99,
            'shipping_cost' => 12.59,
            'description' => 'Samsung LED TV',
            'category_id' => 4,
            'brand_id' => 4,
            'image_path' => 'samsung-led-24.png'
        ]);

        Product::create([
            'name' => 'Samsung Digital Camera',
            'slug' => 'samsung-mv800',
            'details' => '16.1MP, 5x Optical Zoom',
            'price' => 144.99,
            'shipping_cost' => 13.39,
            'description' => 'Samsung Digital Camera',
            'category_id' => 5,
            'brand_id' => 4,
            'image_path' => 'samsung-mv800.jpg'
        ]);

        Product::create([
            'name' => 'Huawei GR 5 2017',
            'slug' => 'gr5-2017',
            'details' => '5.5 inch, 32GB 4GB RAM',
            'price' => 148.99,
            'shipping_cost' => 6.79,
            'description' => 'Huawei GR 5 2017',
            'category_id' => 2,
            'brand_id' => 5,
            'image_path' => 'gr5-2017.jpg'
        ]);
    }
}
/*
    public function run()
    {
        $location = [

            [
                'id' => '1',
                'province' => 'Bulawayo',
                'district' => 'Bulawayo',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '2',
                'province' => 'Harare',
                'district' => 'Harare',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '3',
                'province' => 'Manicaland',
                'district' => 'Chipinge',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '4',
                'province' => 'Manicaland',
                'district' => 'Nyanga',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '5',
                'province' => 'Manicaland',
                'district' => 'Mutare',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '6',
                'province' => 'Manicaland',
                'district' => 'Buhera',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '7',
                'province' => 'Manicaland',
                'district' => 'Mutasa',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '8',
                'province' => 'Manicaland',
                'district' => 'Makoni',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '9',
                'province' => 'Manicaland',
                'district' => 'Chimanimani',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '10',
                'province' => 'Mashonaland Central',
                'district' => 'Mbire',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '11',
                'province' => 'Mashonaland Central',
                'district' => 'Mukumbura',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '12',
                'province' => 'Mashonaland Central',
                'district' => 'Guruve',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '13',
                'province' => 'Mashonaland Central',
                'district' => 'Mazowe',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '14',
                'province' => 'Mashonaland Central',
                'district' => 'Shamva',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '15',
                'province' => 'Mashonaland Central',
                'district' => 'Bindura',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '16',
                'province' => 'Mashonaland Central',
                'district' => 'Muzarabani',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '17',
                'province' => 'Mashonaland Central',
                'district' => 'Rushinga',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '18',
                'province' => 'Mashonaland East',
                'district' => 'Hwedza (Wedza)',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '19',
                'province' => 'Mashonaland East',
                'district' => 'Marondera',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '20',
                'province' => 'Mashonaland East',
                'district' => 'Goromonzi',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '21',
                'province' => 'Mashonaland East',
                'district' => 'Mudzi',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '22',
                'province' => 'Mashonaland East',
                'district' => 'Murehwa',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '23',
                'province' => 'Mashonaland East',
                'district' => 'Chitungwiza',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '24',
                'province' => 'Mashonaland East',
                'district' => 'Mutoko',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '25',
                'province' => 'Mashonaland East',
                'district' => 'Chikomba',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '26',
                'province' => 'Mashonaland East',
                'district' => 'Seke',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '27',
                'province' => 'Mashonaland East',
                'district' => 'Uzumba-Maramba-Pfungwe',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '28',
                'province' => 'Mashonaland West',
                'district' => 'Makonde',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '29',
                'province' => 'Mashonaland West',
                'district' => 'Kadoma',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '30',
                'province' => 'Mashonaland West',
                'district' => 'Chegutu',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '31',
                'province' => 'Mashonaland West',
                'district' => 'Zvimba',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '32',
                'province' => 'Mashonaland West',
                'district' => 'Hurungwe',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '33',
                'province' => 'Mashonaland West',
                'district' => 'Kariba',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '34',
                'province' => 'Masvingo',
                'district' => 'Gutu',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '35',
                'province' => 'Masvingo',
                'district' => 'Chivi',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '36',
                'province' => 'Masvingo',
                'district' => 'Mwenezi',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '37',
                'province' => 'Masvingo',
                'district' => 'Chiredzi',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '38',
                'province' => 'Masvingo',
                'district' => 'Zaka',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '39',
                'province' => 'Masvingo',
                'district' => 'Masvingo',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '40',
                'province' => 'Masvingo',
                'district' => 'Bikita',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '41',
                'province' => 'Matabeleland North',
                'district' => 'Binga',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '42',
                'province' => 'Matabeleland North',
                'district' => 'Bubi',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '43',
                'province' => 'Matabeleland North',
                'district' => 'Lupane',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '44',
                'province' => 'Matabeleland North',
                'district' => 'Nkayi',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '45',
                'province' => 'Matabeleland North',
                'district' => 'Umguza',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '46',
                'province' => 'Matabeleland North',
                'district' => 'Tsholotsho',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '47',
                'province' => 'Matabeleland North',
                'district' => 'Hwange',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '48',
                'province' => 'Matabeleland South',
                'district' => 'Beitbridge',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '49',
                'province' => 'Matabeleland South',
                'district' => 'Umzingwane',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '50',
                'province' => 'Matabeleland South',
                'district' => 'Matobo',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '51',
                'province' => 'Matabeleland South',
                'district' => 'Insiza',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '52',
                'province' => 'Matabeleland South',
                'district' => 'Gwanda',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '53',
                'province' => 'Matabeleland South',
                'district' => 'Bulilimamangwe',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '54',
                'province' => 'Midlands',
                'district' => 'Chirumhanzu',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '55',
                'province' => 'Midlands',
                'district' => 'Gokwe North',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '56',
                'province' => 'Midlands',
                'district' => 'Gokwe South',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '57',
                'province' => 'Midlands',
                'district' => 'Gweru',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '58',
                'province' => 'Midlands',
                'district' => 'Kwekwe',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '59',
                'province' => 'Midlands',
                'district' => 'Mberengwa',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '60',
                'province' => 'Midlands',
                'district' => 'Shurugwi',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '61',
                'province' => 'Midlands',
                'district' => 'Zvishavane',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ],
            [
                'id' => '62',
                'province' => 'Not Specified',
                'district' => 'Not Specified',
                'status' => true,
                'created_at' => '2020-08-21 19:14:42',
                'updated_at' => '2020-08-21 19:14:42',
            ]
        ];

        Location::insert($location);
    }
*/



